export const TIMEOUTS = {
  INITIAL_DELAY: 2000,
  DOM_DETECTION_DELAY: 1000,
  PLAYER_CARDS_WAIT_DELAY: 500,
  MAX_PLAYER_CARDS_WAIT_TIME: 10000,
  MOUSE_LEAVE_DELAY: 150,
  POLLING_INTERVAL: 200,
} as const;

export const DOM_SELECTORS = {
  PLAYER_BUTTONS: '[type="button"][aria-haspopup="dialog"]',
  AVATARS: 'img[aria-label="avatar"]',
  PLAYER_CARDS: [
    '[class*="PlayerCard"]',
    '[class*="ListContentPlayer"]',
    '[class*="Roster__Player"]',
    '[class*="Player__Container"]',
  ],
  ADDITIONAL_PLAYER_CARDS: [
    '[class*="player"]',
    '[class*="Player"]',
    '[class*="roster"]',
    '[class*="Roster"]',
    '[class*="team"]',
    '[class*="Team"]',
    '[data-testid*="player"]',
    '[data-testid*="Player"]',
  ],
  NICKNAME_SELECTORS: [
    '[class*="Nickname"]',
    '[class*="Name"]',
    '[class*="username"]',
    '[class*="Username"]',
    '[data-testid*="nickname"]',
    '[data-testid*="name"]',
    '[data-testid*="username"]',
  ],
  EXISTING_INDICATORS: "[data-refreak-smurf-indicator]",
  LOADING_INDICATORS: "[data-refreak-smurf-loading]",
  HEADER_LOADING_INDICATORS: "[data-refreak-smurf-loading-header]",
  PROCESSED_CARDS: "[data-refreak-smurf-processed]",
  LOADER_PROCESSED_CARDS: "[data-refreak-loader-processed]",
  PLAYER_CARD_BACKGROUND: '[class*="ListContentPlayer__Background"]',
  PLAYER_CARD_HOLDER: '[class*="ListContentPlayer__Holder"]',
  NICKNAME_NAME: '[class*="Nickname__Name"]',
} as const;

export const SMURF_ANALYSIS_THRESHOLDS = {
  VERY_LOW_MATCHES: 30,
  LOW_MATCHES: 100,
  MODERATE_MATCHES: 200,
  AVERAGE_MATCHES: 350,
  HIGH_KD_RATIO: 2.5,
  VERY_HIGH_KD_RATIO: 2.0,
  GOOD_KD_RATIO: 1.5,
  ABOVE_AVERAGE_KD_RATIO: 1.2,
  BASIC_KD_RATIO: 1.0,
  HIGH_WIN_RATE: 85,
  VERY_HIGH_WIN_RATE: 75,
  GOOD_WIN_RATE: 65,
  ABOVE_AVERAGE_WIN_RATE: 55,
  BASIC_WIN_RATE: 45,
  LOW_LEVEL: 3,
  MODERATE_LEVEL: 5,
  AVERAGE_LEVEL: 8,
  HIGH_LEVEL: 12,
  VERY_HIGH_LEVEL: 20,
  HIGH_HEADSHOT_PERCENTAGE: 60,
  HIGH_ADR: 100,
  MIN_CONFIDENCE_THRESHOLD: 51,
} as const;

export const CONFIDENCE_SCORES = {
  VERY_LOW_MATCHES: 40,
  LOW_MATCHES: 30,
  MODERATE_MATCHES: 20,
  AVERAGE_MATCHES: 10,
  EXTREMELY_HIGH_KD: 35,
  VERY_HIGH_KD: 30,
  HIGH_KD: 25,
  ABOVE_AVERAGE_KD: 15,
  GOOD_KD: 10,
  HIGH_WIN_RATE: 25,
  VERY_HIGH_WIN_RATE: 20,
  GOOD_WIN_RATE: 15,
  ABOVE_AVERAGE_WIN_RATE: 10,
  BASIC_WIN_RATE: 5,
  CLASSIC_SMURF_PATTERN: 20,
  HIGH_KR_WITH_LOW_MATCHES: 15,
  HIGH_HEADSHOT: 10,
  HIGH_ADR_SCORE: 10,
  VERY_LOW_LEVEL: 25,
  LOW_LEVEL: 20,
  MODERATE_LEVEL: 15,
  AVERAGE_LEVEL: 10,
  HIGH_LEVEL: 5,
} as const;

export const DEFAULT_SMURF_CONFIG = {
  minMatches: 50,
  maxMatches: 2000,
  minKDRatio: 1,
  minWinRate: 55,
  maxAccountAge: 365,
  suspiciousLevels: [1, 2, 3, 4] as number[],
} as const;
